#### `.github/workflows/build-test.yaml`
name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/php/Dockerfile
        tags: ${{ secrets.DOCKER_REPO }}/laravel-app:pr-${{ github.event.number }}
        push: ${{ github.event_name == 'pull_request' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run PHPUnit tests
      run: |
        docker run --rm -v $(pwd):/app -w /app php:8.2-cli \
          ./vendor/bin/phpunit